name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths:
      - 'Dockerfile'
      - 'cmd/**'
      - 'api/**'
      - 'internal/**'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/docker-publish.yml'
  pull_request:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version
        id: vars
        run: |
          echo "version=$(grep '^VERSION ?=' Makefile | awk '{print $3}')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            docker.io/seredavin/loadtest-operator:latest
            docker.io/seredavin/loadtest-operator:${{ steps.vars.outputs.version }}
