name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint Code
    runs-on: self-hosted
    steps:
      - name: Fix permissions for bin
        run: |
          chmod -R u+w /home/docker/actions-runner/_work/loadtest-operator/loadtest-operator/bin || true

      - name: Show current user
        run: |
          whoami
          id
          ls -l /home/docker/actions-runner/_work/loadtest-operator/loadtest-operator/bin
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.0
